name: CI/CD Workflow

on:
  push:
    branches: [ master, dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t bysxx/typestack-template:latest .
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push bysxx/typestack-template:latest
    
    - name: Deploy to Oracle Cloud
      env:
        PRIVATE_KEY: ${{ secrets.ORACLE_CLOUD_PRIVATE_KEY }}
        HOST: ${{ secrets.ORACLE_CLOUD_USER }}@${{ secrets.ORACLE_CLOUD_IP }}
      run: |
        # SSH key 저장 및 권한 설정
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Docker Hub에서 이미지를 pull하고 실행하는 SSH 명령
        ssh -o StrictHostKeyChecking=no -i private_key.pem $HOST << EOF
          docker pull bysxx/typestack-template:latest
          docker stop typestack-template
          docker rm typestack-template
          docker run -d --name typestack-template -p 3200:3200 bysxx/typestack-template:latest
        EOF
